[build]
  command = "npm install"
  publish = "public"
  functions = "."

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server-render"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
