services:
  - type: web
    name: google-meet-saas-v2
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server-render.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 100 